// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADIZfdqI1uTERWLIpdMIl2dsOPcIBPZO0',
    appId: '1:697886340507:web:3446417f3fdfaa9447dd3e',
    messagingSenderId: '697886340507',
    projectId: 'the-chronicler-8b251',
    authDomain: 'the-chronicler-8b251.firebaseapp.com',
    storageBucket: 'the-chronicler-8b251.firebasestorage.app',
    measurementId: 'G-BTG7371WKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHz1muKAuX9OIDPaZDdyh8AWsTbYiD-fw',
    appId: '1:697886340507:android:5c17627e1ef8b80a47dd3e',
    messagingSenderId: '697886340507',
    projectId: 'the-chronicler-8b251',
    storageBucket: 'the-chronicler-8b251.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2IicF9mAotyeOLyT2Y385NIWz5rbirdY',
    appId: '1:697886340507:ios:d96dc7be04ba8d7047dd3e',
    messagingSenderId: '697886340507',
    projectId: 'the-chronicler-8b251',
    storageBucket: 'the-chronicler-8b251.firebasestorage.app',
    iosBundleId: 'com.abdosalah.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2IicF9mAotyeOLyT2Y385NIWz5rbirdY',
    appId: '1:697886340507:ios:e5c39b4c3e8ef3cc47dd3e',
    messagingSenderId: '697886340507',
    projectId: 'the-chronicler-8b251',
    storageBucket: 'the-chronicler-8b251.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADIZfdqI1uTERWLIpdMIl2dsOPcIBPZO0',
    appId: '1:697886340507:web:754d5ad52ff2286247dd3e',
    messagingSenderId: '697886340507',
    projectId: 'the-chronicler-8b251',
    authDomain: 'the-chronicler-8b251.firebaseapp.com',
    storageBucket: 'the-chronicler-8b251.firebasestorage.app',
    measurementId: 'G-WSQ7S4ZD7G',
  );

}